apiVersion: v1
kind: Pod
metadata:
  name: openshift-etcd
  namespace: openshift-etcd
  labels:
    app: etcd
    etcd: "true"
    revision: "REVISION"
spec:
  containers:
  - name: openshift-etcd
    image: ${IMAGE}
    imagePullPolicy: Always
    terminationMessagePolicy: FallbackToLogsOnError
    command: ["sleep"]
    args:
    - "7200"
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
    ports:
      - containerPort: 2379
        name: client
        protocol: TCP
    ports:
      - containerPort: 2380
        name: peer
        protocol: TCP
    volumeMounts:
    - name: discovery
      mountPath: /run/etcd/
    - name: certs
      mountPath: /etc/ssl/etcd/
    - name: data-dir
      mountPath: /var/lib/etcd/
    - name: resource-dir
      mountPath: /etc/kubernetes/static-pod-resources
#    livenessProbe:
#      httpGet:
#        scheme: HTTPS
#        port: 10257
#        path: healthz
#      initialDelaySeconds: 45
#      timeoutSeconds: 10
#    readinessProbe:
#      httpGet:
#        scheme: HTTPS
#        port: 10257
#        path: healthz
#      initialDelaySeconds: 10
#      timeoutSeconds: 10
  hostNetwork: true
  priorityClassName: system-node-critical
  tolerations:
  - operator: "Exists"
  volumes:
  - name: resource-dir
    hostPath:
      path: /etc/kubernetes/static-pod-resources/etcd-pod-REVISION
  - name: certs
    hostPath:
      path: /etc/kubernetes/static-pod-resources/etcd-member
  - name: discovery
    hostPath:
      path: /run/etcd
  - name: data-dir
    hostPath:
      path: /var/lib/etcd
