---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-etcd-operator-staticpod
rules:
- apiGroups: ["machineconfiguration.openshift.io"]
  resources: ["machineconfigpools", "machineconfigs"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cluster-etcd-operator-staticpod
  namespace: openshift-etcd
subjects:
- kind: ServiceAccount
  name: default
  namespace: openshift-etcd
roleRef:
  kind: ClusterRole
  namespace: openshift-etcd
  name: cluster-etcd-operator-staticpod
  apiVersion: rbac.authorization.k8s.io/v1beta1
