apiVersion: v1
kind: Pod
metadata:
  name: openshift-etcd
  namespace: openshift-etcd
  labels:
    app: etcd
    etcd: "true"
    revision: "REVISION"
spec:
  containers:
  - name: openshift-etcd
    image: ${IMAGE}
    imagePullPolicy: Always
    terminationMessagePolicy: FallbackToLogsOnError
    command: ["sleep"]
    args:
    - "7200"
    resources:
      requests:
        memory: 200Mi
        cpu: 100m
    ports:
      - containerPort: 10257
    volumeMounts:
    - mountPath: /etc/kubernetes/static-pod-resources
      name: resource-dir
#    livenessProbe:
#      httpGet:
#        scheme: HTTPS
#        port: 10257
#        path: healthz
#      initialDelaySeconds: 45
#      timeoutSeconds: 10
#    readinessProbe:
#      httpGet:
#        scheme: HTTPS
#        port: 10257
#        path: healthz
#      initialDelaySeconds: 10
#      timeoutSeconds: 10
  hostNetwork: true
  priorityClassName: system-node-critical
  tolerations:
  - operator: "Exists"
  volumes:
  - hostPath:
      path: /etc/kubernetes/static-pod-resources/etcd-pod-REVISION
    name: resource-dir

