apiVersion: v1
kind: ConfigMap
metadata:
  # this CA bundle is a placeholder and is mounted by the operator
  # it will later be populated by the resourcesynccontroller
  name: etcd-ca-bundle
  namespace: openshift-etcd-operator
data:
  ca-bundle.crt: |
    stub

